// Author: Preston Lee

/**
 * Extract 30y CVD F/M percentile tables from Krishnan JACC 2025 mmc2.xlsx.
 *
 * Usage: npx tsx scripts/extract-prevent-percentiles.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as XLSX from 'xlsx';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const XLSX_PATH = resolve(
  ROOT,
  'doc/private/30-Year Paper/1-s2.0-S0735109725093179-mmc2.xlsx',
);
const OUT_JSON = resolve(
  ROOT,
  'src/app/features/open-cvd-risk-calculator/prevent/prevent-30y-cvd-percentiles.json',
);
const OUT_TS = resolve(
  ROOT,
  'src/app/features/open-cvd-risk-calculator/prevent/prevent-30y-cvd-percentiles.ts',
);

type SexKey = 'female' | 'male';

interface ExtractedTables {
  source: string;
  ages: number[];
  /** Per sex: age (as string) → risks[0]=1st percentile … risks[98]=99th (99th is 100%). */
  bySexAge: Record<SexKey, Record<string, number[]>>;
}

function extractSheet(wb: XLSX.WorkBook, sheetName: string): {
  ages: number[];
  byAge: Record<string, number[]>;
} {
  const ws = wb.Sheets[sheetName];
  if (!ws) {
    throw new Error(`Missing sheet ${sheetName}`);
  }
  const data = XLSX.utils.sheet_to_json(ws, { header: 1, raw: true }) as unknown[][];
  if (data.length < 100) {
    throw new Error(`${sheetName}: expected ≥100 rows, got ${data.length}`);
  }
  const header = data[0] as unknown[];
  const ages: number[] = [];
  for (let c = 1; c < header.length; c++) {
    const age = Number(header[c]);
    if (!Number.isInteger(age) || age < 30 || age > 59) {
      throw new Error(`${sheetName}: unexpected age header at col ${c}: ${header[c]}`);
    }
    ages.push(age);
  }
  const byAge: Record<string, number[]> = {};
  for (const age of ages) {
    byAge[String(age)] = [];
  }
  for (let r = 1; r <= 99; r++) {
    const row = data[r] as unknown[];
    const pct = Number(row[0]);
    if (pct !== r) {
      throw new Error(`${sheetName}: row ${r} percentile is ${row[0]}, expected ${r}`);
    }
    for (let i = 0; i < ages.length; i++) {
      const risk = Number(row[i + 1]);
      if (!Number.isFinite(risk)) {
        throw new Error(`${sheetName}: non-finite risk at percentile ${r} age ${ages[i]}`);
      }
      byAge[String(ages[i]!)]!.push(risk);
    }
  }
  for (const age of ages) {
    const risks = byAge[String(age)]!;
    if (risks.length !== 99) {
      throw new Error(`${sheetName}: age ${age} has ${risks.length} percentiles`);
    }
    if (risks[98] !== 100) {
      throw new Error(`${sheetName}: age ${age} 99th percentile must be 100, got ${risks[98]}`);
    }
  }
  return { ages, byAge };
}

function main(): void {
  const wb = XLSX.readFile(XLSX_PATH);
  const female = extractSheet(wb, '30y CVD F');
  const male = extractSheet(wb, '30y CVD M');
  if (female.ages.join(',') !== male.ages.join(',')) {
    throw new Error('Female and male age columns differ');
  }
  const out: ExtractedTables = {
    source:
      'Krishnan et al. JACC 2025 supplemental mmc2.xlsx (30y CVD F/M); regenerated by scripts/extract-prevent-percentiles.ts',
    ages: female.ages,
    bySexAge: {
      female: female.byAge,
      male: male.byAge,
    },
  };
  mkdirSync(dirname(OUT_JSON), { recursive: true });
  writeFileSync(OUT_JSON, JSON.stringify(out, null, 2) + '\n', 'utf8');
  const tsBody =
    '// Author: Preston Lee\n\n' +
    '/** 30y CVD F/M percentile tables from Krishnan JACC 2025 mmc2. Regenerated by scripts/extract-prevent-percentiles.ts */\n' +
    `export const PREVENT_30Y_CVD_PERCENTILES = ${JSON.stringify(out, null, 2)} as const;\n`;
  writeFileSync(OUT_TS, tsBody, 'utf8');
  console.log(`Wrote ${OUT_JSON} and ${OUT_TS} (${female.ages.length} ages × 99 percentiles × 2 sexes)`);
}

main();
