// Author: Preston Lee

/**
 * Generate public/cql/SDI-2019.cql from the raw Graham Center ZCTA CSV in doc/sdi/.
 *
 * Usage: npx tsx scripts/generate-sdi-2019.ts
 */

import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSdiZctaCsv, type SdiDecileMap } from '../src/app/features/open-cvd-risk-calculator/sdi/sdi-lookup';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CSV_PATH = resolve(ROOT, 'doc/sdi/asset_rgc_sdi_2015_through_2019_zcta.csv');
const OUT_CQL = resolve(ROOT, 'public/cql/SDI-2019.cql');

function emitCql(mapping: SdiDecileMap): string {
  const whens = Object.keys(mapping)
    .sort()
    .map((z) => `    when '${z}' then ${mapping[z]}`)
    .join('\n');
  const n = Object.keys(mapping).length;
  return `/*
  SDI2019: ZIP Code Tabulation Area (ZCTA) → Social Deprivation Index decile (1-10).

  Source: Robert Graham Center 2019 SDI at ZCTA (2015-2019 ACS 5-year estimates).
  Decile mapping matches preventr (SDI_score centile bands).

  Regenerated by scripts/generate-sdi-2019.ts - do not hand-edit the when map.
  Prefer OverrideZipCode already normalized to 5 digits (digits-only; ZIP+4 stripped).
  Chart postalCode handling is best-effort (hyphen strip + pad). The Angular calculator
  resolves live ZIP→SDI via this library's $evaluate (SdiDecile), not client CSV.

  Author: Preston Lee
*/
library SDI2019 version '1.0.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1'

/* Null / omitted → use Patient.address.postalCode (first 5 chars after optional hyphen trim). */
parameter OverrideZipCode String

context Patient

define HomeAddresses:
  Patient.address A
    where A.use ~ 'home' and A.postalCode is not null

define AnyAddresses:
  Patient.address A
    where A.postalCode is not null

define PatientPostalRaw:
  Coalesce(
    First(HomeAddresses).postalCode,
    First(AnyAddresses).postalCode
  )

define function StripPlus4(raw String):
  if raw is null then null
  else if PositionOf('-', raw) >= 0 then Substring(raw, 0, PositionOf('-', raw))
  else raw

/* Best-effort ZCTA key: strip ZIP+4, then first 5 chars or left-pad short values. */
define function ToZip5(raw String):
  if raw is null or Length(raw) = 0 then
    null
  else
    if Length(StripPlus4(raw)) >= 5 then
      Substring(StripPlus4(raw), 0, 5)
    else if Length(StripPlus4(raw)) = 4 then
      Combine({ '0', StripPlus4(raw) }, '')
    else if Length(StripPlus4(raw)) = 3 then
      Combine({ '00', StripPlus4(raw) }, '')
    else if Length(StripPlus4(raw)) = 2 then
      Combine({ '000', StripPlus4(raw) }, '')
    else if Length(StripPlus4(raw)) = 1 then
      Combine({ '0000', StripPlus4(raw) }, '')
    else
      null

define PatientPostalCode:
  ToZip5(PatientPostalRaw)

define EffectiveZipCode:
  Coalesce(ToZip5(OverrideZipCode), PatientPostalCode)

define function SdiDecileForZip(zip String):
  case zip
${whens}
    else null
  end

define SdiDecile:
  SdiDecileForZip(EffectiveZipCode)

define ZctaMapSize:
  ${n}
`;
}

function main(): void {
  let csvText: string;
  try {
    csvText = readFileSync(CSV_PATH, 'utf8');
  } catch {
    throw new Error(`Missing ${CSV_PATH}`);
  }
  const mapping = parseSdiZctaCsv(csvText);
  const n = Object.keys(mapping).length;
  if (n < 1000) {
    throw new Error(`Suspiciously small map: ${n}`);
  }
  mkdirSync(dirname(OUT_CQL), { recursive: true });
  writeFileSync(OUT_CQL, emitCql(mapping), 'utf8');
  console.log(`Wrote ${OUT_CQL} (${n} ZCTAs, ${statSync(OUT_CQL).size} bytes)`);
}

main();
