// Author: Preston Lee

import { GuidelineRecommendationMeta } from './guideline.model';

/** Exact Recommendation 1–24 catalog from VA/DoD Lipids CPG Dec 2025, Table 4 (pp. 24–26). */
export const GUIDELINE_RECOMMENDATIONS: readonly GuidelineRecommendationMeta[] = [
  {
    id: 1,
    text: 'We suggest using the Predicting Risk of CVD EVENTs (PREVENT) calculator to estimate cardiovascular disease risk.',
    strength: 'Weak for',
    category: 'Assessment of CVD Risk',
    pdfPages: '24, 27–28',
    relatedBoxIds: [14],
    relatedSidebars: ['Sidebar 1'],
    displayNote: 'Decision-support risk estimate only; not a prescription.',
  },
  {
    id: 2,
    text: 'There is insufficient evidence to recommend for or against any specific frequency of repeating cardiovascular disease risk assessment.',
    strength: 'Neither for nor against',
    category: 'Assessment of CVD Risk',
    pdfPages: '24, 28–29',
    relatedBoxIds: [14],
    relatedSidebars: [],
    displayNote:
      'Algorithm Box 14 practice point (every 5 years) is separate from this recommendation’s insufficient-evidence stance.',
  },
  {
    id: 3,
    text: 'For patients at intermediate to high clinical risk of atherosclerotic cardiovascular disease, in whom the decision about whether to initiate or intensify lipid therapy is uncertain and would be changed based on coronary artery calcium testing results, we suggest coronary artery calcium testing.',
    strength: 'Weak for',
    category: 'Novel Markers',
    pdfPages: '24, 30–32',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 2'],
    displayNote: 'Requires clinician confirmation of intermediate/high risk and that CAC would change management.',
  },
  {
    id: 4,
    text: 'For patients at low clinical risk of atherosclerotic cardiovascular disease, we suggest against coronary artery calcium testing.',
    strength: 'Weak against',
    category: 'Novel Markers',
    pdfPages: '24, 30–32',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 2'],
    displayNote: 'Requires clinician confirmation of low clinical risk.',
  },
  {
    id: 5,
    text: 'We suggest testing for lipoprotein(a) once in a patient’s lifetime.',
    strength: 'Weak for',
    category: 'Novel Markers',
    pdfPages: '24, 33–34',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 2'],
    displayNote: 'Do not insert Lp(a) into PREVENT equations.',
  },
  {
    id: 6,
    text: 'There is insufficient evidence to recommend for or against testing for the ankle-brachial index, apolipoprotein B, polygenic risk score, total plaque area, or high-sensitivity C-reactive protein to assess cardiovascular disease risk.',
    strength: 'Neither for nor against',
    category: 'Novel Markers',
    pdfPages: '24, 34–36',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 2'],
    displayNote: 'Informational insufficient-evidence statement.',
  },
  {
    id: 7,
    text: 'For primary prevention in patients with diabetes mellitus, a low-density lipoprotein cholesterol level ≥190 mg/dL, or a 10-year estimated risk of cardiovascular disease ≥10%, we recommend a moderate-intensity statin at a minimum.',
    strength: 'Strong for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 37–40',
    relatedBoxIds: [8, 9],
    relatedSidebars: ['Sidebar 5'],
    displayNote: 'Option set / intensity guidance only; not an order.',
  },
  {
    id: 8,
    text: 'For primary prevention in patients with a 10-year estimated risk of cardiovascular disease of ≥5% and <10%, we suggest a moderate-intensity statin after shared decision making.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 40–41',
    relatedBoxIds: [10, 12, 11],
    relatedSidebars: ['Sidebar 5'],
    displayNote:
      'Applicability remains visible in the 5%–<10% band even if Box 12 preference is unresolved or No; Box 11 path requires desire Yes.',
  },
  {
    id: 9,
    text: 'There is insufficient evidence to recommend for or against icosapent ethyl for primary prevention of cardiovascular disease.',
    strength: 'Neither for nor against',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 41–42',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 8'],
    displayNote: 'Informational; primary-prevention IPE uncertainty.',
  },
  {
    id: 10,
    text: 'For primary prevention in patients with human immunodeficiency virus with a low 10-year estimated risk of cardiovascular disease (<5%), we suggest a moderate-intensity statin with a low risk of antiretroviral interaction.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 42–44',
    relatedBoxIds: [10, 11],
    relatedSidebars: ['Sidebar 5'],
    displayNote: 'Include antiretroviral interaction counseling; not an order.',
  },
  {
    id: 11,
    text: 'For patients with an indication for a statin and baseline aspartate aminotransferase and alanine aminotransferase levels <3 times the upper limit of normal, we suggest initiating statin therapy without further hepatic testing or referral.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '25, 44–45',
    relatedBoxIds: [9, 11],
    relatedSidebars: [],
    displayNote: 'Requires AST/ALT reference-range evidence or clinician confirmation of <3× ULN.',
  },
  {
    id: 12,
    text: 'We suggest against adding fibrates to statin therapy.',
    strength: 'Weak against',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '25, 45–46',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 8'],
    displayNote: 'Weak-against cue; decision support only.',
  },
  {
    id: 13,
    text: 'For secondary prevention in patients not at very high risk, we suggest one of the following: a high-intensity statin; a moderate-intensity statin with ezetimibe; or a moderate-intensity statin with a PCSK9 inhibitor.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 47–50',
    relatedBoxIds: [16],
    relatedSidebars: ['Sidebar 3', 'Sidebar 5', 'Sidebar 6'],
    displayNote: 'Unranked option set; shared decision-making required. Not a prescription.',
  },
  {
    id: 14,
    text: 'For secondary prevention in patients at very high risk, we suggest one of the following: a high-intensity or maximally tolerated statin with ezetimibe; or a high-intensity or maximally tolerated statin with a PCSK9 inhibitor. If additional lipid lowering is needed, we suggest a high-intensity or maximally tolerated statin with ezetimibe and a PCSK9 inhibitor.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 50–53',
    relatedBoxIds: [17, 18, 19],
    relatedSidebars: ['Sidebar 4', 'Sidebar 5', 'Sidebar 6'],
    displayNote: 'Unranked dual- then triple-therapy option set; escalation is clinician judgment (Box 18).',
  },
  {
    id: 15,
    text: 'For patients on lipid-lowering therapy with a low-density lipoprotein cholesterol level <30 mg/dL, we suggest continuing treatment.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 53–54',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote:
      'Distinct from Box 15 (reassess when new risk factors develop). This recommendation addresses LDL-C <30 mg/dL while on therapy.',
  },
  {
    id: 16,
    text: 'For secondary prevention in patients on a statin with persistently elevated fasting triglycerides ≥150 mg/dL, after secondary causes have been addressed, we suggest adding icosapent ethyl.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 54–56',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 8'],
    displayNote: 'Persistence and secondary causes require clinician confirmation when chart data are ambiguous.',
  },
  {
    id: 17,
    text: 'There is insufficient evidence to recommend for or against a fixed-dose strategy versus a treat-to-target strategy for lipid-lowering therapy.',
    strength: 'Neither for nor against',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 56–57',
    relatedBoxIds: [20],
    relatedSidebars: [],
    displayNote: 'Box 20 presents both monitoring strategies without preferring either.',
  },
  {
    id: 18,
    text: 'For patients with statin intolerance, we suggest a rechallenge with a statin (same or different statin, same or lower dose, or intermittent dosing) before switching to a non-statin lipid-lowering therapy.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 57–58',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 7'],
    displayNote: 'Statin intolerance is clinician-confirmed.',
  },
  {
    id: 19,
    text: 'For patients unable to take a statin, we suggest ezetimibe, a PCSK9 inhibitor, or bempedoic acid.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 58–59',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 6', 'Sidebar 7'],
    displayNote: 'Unable-to-take-statin is clinician-confirmed; unranked options; not an order.',
  },
  {
    id: 20,
    text: 'There is insufficient evidence to recommend for or against dietary supplements (e.g., red yeast rice, berberine, fish oil) for lipid lowering or cardiovascular disease risk reduction.',
    strength: 'Neither for nor against',
    category: 'Supplements',
    pdfPages: '26, 59–60',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote: 'Informational insufficient-evidence statement.',
  },
  {
    id: 21,
    text: 'We suggest against omega-3 fatty acid supplements (other than icosapent ethyl) for lipid lowering or cardiovascular disease risk reduction.',
    strength: 'Weak against',
    category: 'Supplements',
    pdfPages: '26, 60–61',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 8'],
    displayNote: 'Weak against non-IPE omega-3 products.',
  },
  {
    id: 22,
    text: 'We recommend a Mediterranean diet to reduce cardiovascular disease risk.',
    strength: 'Strong for',
    category: 'Lifestyle',
    pdfPages: '26, 61–63',
    relatedBoxIds: [2, 21],
    relatedSidebars: [],
    displayNote: 'Universal lifestyle recommendation; Boxes 2 and 21 re-emphasize lifestyle.',
  },
  {
    id: 23,
    text: 'We recommend physical activity of at least moderate intensity for ≥150 minutes per week, or as much as the patient’s health status allows, to reduce cardiovascular disease risk.',
    strength: 'Strong for',
    category: 'Lifestyle',
    pdfPages: '26, 63–64',
    relatedBoxIds: [2, 21],
    relatedSidebars: [],
    displayNote: 'Universal lifestyle recommendation.',
  },
  {
    id: 24,
    text: 'For patients with recent coronary heart disease (myocardial infarction, acute coronary syndrome, coronary artery bypass graft, or percutaneous coronary intervention), we recommend referral to a comprehensive cardiac rehabilitation program.',
    strength: 'Strong for',
    category: 'Lifestyle',
    pdfPages: '26, 61–62',
    relatedBoxIds: [6],
    relatedSidebars: [],
    displayNote:
      'Broader “recent CHD” population than Box 6’s concurrent six-week MI/ACS/CABG/PCI referral cue.',
  },
];
