// Author: Preston Lee

import { GuidelineRecommendationMeta } from './guideline.model';

/** Recommendation 1–24 from VA/DoD Lipids CPG Dec 2025, Table 4 (pp. 24–26). `text` is Table 4 only. */
export const GUIDELINE_RECOMMENDATIONS: readonly GuidelineRecommendationMeta[] = [
  {
    id: 1,
    text: 'For cardiovascular risk assessment in primary prevention, we suggest the PREVENT risk assessment tool.',
    strength: 'Weak for',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 27–28',
    relatedBoxIds: [14],
    relatedSidebars: [],
    displayNote:
      'Decision-support risk estimate only; not a prescription. PREVENT is Rec 1 and Appendix H, not a numbered sidebar.',
  },
  {
    id: 2,
    text: 'For primary prevention, in patients over 18 and not on statin therapy who have not developed new cardiovascular risk factors (e.g., diabetes, hypertension, tobacco use), there is insufficient evidence to recommend for or against a specific frequency for cardiovascular disease risk assessment.',
    strength: 'Neither for nor against',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 28–29',
    relatedBoxIds: [14],
    relatedSidebars: [],
    displayNote:
      'Algorithm Box 14 practice point (every 5 years) is separate from this recommendation’s insufficient-evidence stance. Rec 2 discussion notes it is reasonable to assess every 5 years in the absence of new risk factors.',
  },
  {
    id: 3,
    text: 'For primary prevention, in patients identified with intermediate to high risk, we suggest coronary artery calcium testing to improve the accuracy of risk assessment when deemed to affect clinical decision-making.',
    strength: 'Weak for',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 30–32',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 7'],
    displayNote:
      'Table 4 footnote: read the narrative for intermediate to high risk. Do not bind a PREVENT cutoff. Requires clinician confirmation of intermediate/high risk and that CAC would affect decision-making.',
  },
  {
    id: 4,
    text: 'For patients with low risk, we suggest against the routine use of coronary artery calcium testing.',
    strength: 'Weak against',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 30–32',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 7'],
    displayNote: 'Requires clinician confirmation of low clinical risk.',
  },
  {
    id: 5,
    text: 'We suggest measuring lipoprotein(a) [Lp(a)] to identify patients with enhanced risk.',
    strength: 'Weak for',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 31–33',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 7'],
    displayNote:
      'Rec 5 discussion: measuring Lp(a) at least once is justified. Do not insert Lp(a) into PREVENT equations.',
  },
  {
    id: 6,
    text: 'There is insufficient evidence to recommend for or against the routine use of ankle brachial index (ABI), apolipoprotein B (ApoB), polygenic risk scores (PRS), carotid plaque/total carotid plaque area (TPA), and high-sensitivity C-reactive protein (hs-CRP) for estimating cardiovascular risk.',
    strength: 'Neither for nor against',
    category: 'Screening and Assessment of Cardiovascular Risk',
    pdfPages: '24, 33–36',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 7'],
    displayNote: 'Informational insufficient-evidence statement.',
  },
  {
    id: 7,
    text: 'For primary prevention among patients who have diabetes or 10-year cardiovascular risk ≥10% or low-density lipoprotein cholesterol (LDL-C) ≥190 mg/dL, we recommend using at least a moderate-intensity statin.',
    strength: 'Strong for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 36–40',
    relatedBoxIds: [8, 9],
    relatedSidebars: ['Sidebar 5'],
    displayNote: 'Option set / intensity guidance only; not an order.',
  },
  {
    id: 8,
    text: 'For primary prevention among patients without diabetes who have low-density lipoprotein cholesterol (LDL-C) <190 mg/dL and a 10-year cardiovascular risk between approximately 5% to less than 10%, we suggest using a moderate-intensity statin.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '24, 36–41',
    relatedBoxIds: [12, 11],
    relatedSidebars: ['Sidebar 5'],
    displayNote:
      'Applicability remains visible in the 5%–<10% band even if Box 12 preference is unresolved or No; Box 11 path requires desire Yes. Appendix G Box 11 is the shared moderate-statin node for Recs 8 and 10.',
  },
  {
    id: 9,
    text: 'For primary prevention, there is insufficient evidence to recommend for or against icosapent ethyl in patients on statin therapy with persistently elevated fasting triglycerides ≥150 mg/dL.',
    strength: 'Neither for nor against',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '25, 38–42',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote: 'Informational; primary-prevention IPE uncertainty. Sidebar 8 is secondary prevention.',
  },
  {
    id: 10,
    text: 'For primary prevention in patients with human immunodeficiency virus (HIV), we suggest a moderate-intensity statin that has a low risk of interactions with antiretroviral therapy, even when 10-year risk estimates are low (i.e., <5%).',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '25, 39–44',
    relatedBoxIds: [10, 11],
    relatedSidebars: ['Sidebar 5'],
    displayNote:
      '“Even when … <5%” does not limit Rec 10 to the low-risk band. Overlap with Rec 7 on the Box 8 Yes path is intended. Not an order.',
  },
  {
    id: 11,
    text: 'In patients with an indication for statin therapy and elevated baseline aspartate aminotransferase (AST) or alanine transaminase (ALT) less than 3-times the upper limit of normal, we suggest using statins as indicated.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Primary Prevention',
    pdfPages: '25, 41–45',
    relatedBoxIds: [9, 11],
    relatedSidebars: [],
    displayNote:
      'Evidence population is mildly elevated LFTs (1–3× ULN), not normal labs. Requires a statin indication and clinician confirmation of that LFT pattern.',
  },
  {
    id: 12,
    text: 'For primary or secondary prevention, we suggest against adding fibrates to statins.',
    strength: 'Weak against',
    category: 'Pharmacotherapy',
    pdfPages: '25, 42–46',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote: 'Weak-against cue; decision support only. Rec 19 still lists fibrates when the patient is unable to take a statin.',
  },
  {
    id: 13,
    text: 'For secondary prevention, we suggest treating with one of the following: high-intensity statin; moderate-intensity statin with ezetimibe; moderate-intensity statin with proprotein convertase subtilisin/kexin type 9 (PCSK9) inhibitor.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 43–50',
    relatedBoxIds: [16],
    relatedSidebars: ['Sidebar 3', 'Sidebar 5'],
    displayNote:
      'Table 4 footnote: listed in alphabetical order (unranked). CQL applies Rec 13 when not very high risk (Box 16). Not a prescription.',
  },
  {
    id: 14,
    text: 'For secondary prevention in very high-risk patients, we suggest a combination therapy of one of the following: high-intensity or maximally tolerated statin with ezetimibe; high-intensity or maximally tolerated statin with PCSK9 inhibitor; high-intensity or maximally tolerated statin with ezetimibe and PCSK9 inhibitor.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 46–53',
    relatedBoxIds: [17, 18, 19],
    relatedSidebars: ['Sidebar 4', 'Sidebar 5'],
    displayNote:
      'Table 4 lists three peer options. Appendix G sequences dual therapy (Box 17) then escalation (Box 18/19). Very high risk is Sidebar 4 (all criteria require lipid-lowering therapy).',
  },
  {
    id: 15,
    text: 'For patients who achieve a very low low-density lipoprotein value (LDL-C <30 mg/dL) with therapy, we suggest continuing treatment.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 49–54',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote:
      'Distinct from Box 15 (reassess when new risk factors or enhancers develop). This recommendation addresses LDL-C <30 mg/dL while on therapy.',
  },
  {
    id: 16,
    text: 'For secondary prevention, we suggest icosapent ethyl in patients on statin therapy with persistently elevated fasting triglycerides ≥150 mg/dL.',
    strength: 'Weak for',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 50–56',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 8'],
    displayNote:
      'Table 4 requires on-statin therapy, not necessarily maximally tolerated. Secondary causes, maximally tolerated statin, and IPE 2 g BID are Sidebar 8.',
  },
  {
    id: 17,
    text: 'For secondary prevention, there is insufficient evidence to recommend a treat-to-target strategy (e.g., low-density lipoprotein [LDL-C] <70 mg/dL) over a fixed-dose high-intensity statin strategy.',
    strength: 'Neither for nor against',
    category: 'Pharmacotherapy for Secondary Prevention',
    pdfPages: '25, 51–57',
    relatedBoxIds: [20],
    relatedSidebars: [],
    displayNote: 'Box 20 presents both monitoring strategies without preferring either.',
  },
  {
    id: 18,
    text: 'For patients who cannot tolerate a statin, we suggest a washout period followed by a re-challenge with the same or a different statin or lower dose, and if that fails, a trial of intermittent (nondaily) dosing.',
    strength: 'Weak for',
    category: 'Statin Intolerance',
    pdfPages: '25, 53–58',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 6'],
    displayNote: 'Statin intolerance is clinician-confirmed. Sidebar 6 examples include a 1-month washout and nondaily dosing.',
  },
  {
    id: 19,
    text: 'For primary and secondary prevention in patients unable to take a statin, we suggest one of the following non-statins: bempedoic acid, ezetimibe, fibrates, or proprotein convertase subtilisin/kexin type 9 monoclonal antibody (PCSK9 mAb) inhibitors.',
    strength: 'Weak for',
    category: 'Statin Intolerance',
    pdfPages: '26, 54–59',
    relatedBoxIds: [],
    relatedSidebars: ['Sidebar 6'],
    displayNote:
      'Unable-to-take-statin is clinician-confirmed; unranked options; not an order. Rec 12 still suggests against adding fibrates to a statin.',
  },
  {
    id: 20,
    text: 'There is insufficient evidence to recommend for or against the use of fiber, garlic, ginger, green tea, and red yeast rice supplements to reduce cardiovascular risks.',
    strength: 'Neither for nor against',
    category: 'Supplements',
    pdfPages: '26, 56–60',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote: 'Informational insufficient-evidence statement.',
  },
  {
    id: 21,
    text: 'For primary or secondary prevention, we suggest against the use of omega-3 fatty acids as a dietary supplement or any omega-3 formulation other than icosapent ethyl.',
    strength: 'Weak against',
    category: 'Nutraceuticals',
    pdfPages: '26, 57–61',
    relatedBoxIds: [],
    relatedSidebars: [],
    displayNote: 'Weak against non-IPE omega-3 products. IPE for secondary prevention is Rec 16 / Sidebar 8.',
  },
  {
    id: 22,
    text: 'For primary and secondary prevention of cardiovascular disease, we suggest a Mediterranean diet.',
    strength: 'Weak for',
    category: 'Lifestyle Interventions',
    pdfPages: '26, 59–63',
    relatedBoxIds: [2, 21],
    relatedSidebars: ['Sidebar 1', 'Sidebar 2'],
    displayNote: 'Universal lifestyle recommendation; Boxes 2 and 21 re-emphasize lifestyle.',
  },
  {
    id: 23,
    text: 'For primary and secondary prevention, we suggest increasing regular aerobic physical activity that maximizes what the patient is willing and able to achieve.',
    strength: 'Weak for',
    category: 'Lifestyle Interventions',
    pdfPages: '26, 59–64',
    relatedBoxIds: [2, 21],
    relatedSidebars: ['Sidebar 1'],
    displayNote:
      '150 minutes moderate or 75 minutes vigorous weekly is Sidebar 1 and Rec 23 discussion of PAGA, not this recommendation’s text. Rec 23 is Weak for because activity as tolerated includes below those goals.',
  },
  {
    id: 24,
    text: 'We recommend a structured, exercise-based cardiac rehabilitation program for patients with recent occurrence of coronary heart disease (i.e., myocardial infarction, diagnosis of coronary artery disease, coronary artery bypass grafting, or percutaneous coronary intervention).',
    strength: 'Strong for',
    category: 'Lifestyle Interventions',
    pdfPages: '26, 61–62',
    relatedBoxIds: [6],
    relatedSidebars: [],
    displayNote:
      'Table 4 does not list ACS. Box 6 Yes (MI/ACS/CABG/PCI in the past 6 weeks) is sufficient for Rec 24. Box 6 No does not rule out Rec 24 (recent CAD diagnosis). Rec 24 discussion refers to recently diagnosed CHD.',
  },
];
